"""create table license

Revision ID: 12a336353753
Revises: 976c2ae18f44
Create Date: 2020-07-11 19:34:33.434169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a336353753'
down_revision = '976c2ae18f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('licenses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('license_id', sa.Integer(), nullable=False),
                    sa.Column('assigned', sa.Boolean(), nullable=False),
                    sa.Column('revoked', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('licenses')
    # ### end Alembic commands ###
