"""create table labels

Revision ID: 976c2ae18f44
Revises: 8be537914237
Create Date: 2020-07-11 19:34:18.172296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976c2ae18f44'
down_revision = '8be537914237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.String(length=256), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('labels')
    # ### end Alembic commands ###
